### ISSUE TITLE
Controller: ExternalAuthFacebook Action: logincallback - The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by SilverSearcher** [smartstoreag/SmartStoreNET#1270]
Hi,

Any ideas on why I might be getting this? - Controller: ExternalAuthFacebook Action: logincallback - The remote server returned an error: (400) Bad Request.

AppID/Secret are correct and the app is live.

**Comment by mgesing** [comment]
What is the version of the Facebook plugin? Are there any details logged under System > Log?

**Comment by SilverSearcher** [comment]
Version 3.0.2

System.Net.WebException: The remote server returned an error: (400) Bad Request.
   at System.Net.HttpWebRequest.GetResponse()
   at SmartStore.FacebookAuth.Core.FacebookOAuth2Client.QueryAccessToken(Uri returnUrl, String authorizationCode)
   at SmartStore.FacebookAuth.Core.FacebookOAuth2Client.VerifyAuthentication(HttpContextBase context, Uri returnPageUrl)
   at SmartStore.FacebookAuth.Core.FacebookProviderAuthorizer.VerifyAuthentication(String returnUrl)
   at SmartStore.FacebookAuth.Core.FacebookProviderAuthorizer.Authorize(String returnUrl, Nullable`1 verifyResponse)
   at SmartStore.FacebookAuth.Controllers.ExternalAuthFacebookController.LoginInternal(String returnUrl, Boolean verifyResponse)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

**Comment by mgesing** [comment]
I cannot reproduce that. QueryAccessToken is where the configuration data is required and send to Facebook. I guess it's a problem due to a misconfiguration, either in the .NET plugin configuration or in your Facebook account.
There is a URL whitelist setting in your facebook account. Did you enter your shop URL there? Or try to solve it by deleting and recreating the app in facebook.

**Comment by SilverSearcher** [comment]
My apologies - FB is dumb (or I am) - by default; it has these two setting set to yes and need to be set to no...

Require App Secret
Allow API Access to App Settings

Works perfect now. Apologies again.
