### ISSUE TITLE
Cache memory leak Issues builtin@search-engine-record.com

### ISSUE THREAD

**Issue by andriisydor** [smartstoreag/SmartStoreNET#720]
I have a lot of these log errors

System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Go60(RegexRunner )
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at SmartStore.Core.Infrastructure.AppDomainTypeFinder.Matches(String assemblyFullName)
   at SmartStore.Core.Infrastructure.AppDomainTypeFinder.AddAssembliesInAppDomain(List`1 addedAssemblyNames, List`1 assemblies)
   at SmartStore.Core.Infrastructure.AppDomainTypeFinder.GetAssemblies(Boolean ignoreInactivePlugins)
   at SmartStore.Core.Infrastructure.ITypeFinderExtensions.FindClassesOfType[T](ITypeFinder finder, Boolean onlyConcreteClasses, Boolean ignoreInactivePlugins)
   at SmartStore.Web.Framework.UI.MenuPublisher.<>c__DisplayClass7.<RegisterMenus>b__3()
   at SmartStore.Core.Caching.CacheManager`1.Get[T](String key, Func`1 acquirer, Nullable`1 cacheTime)
   at SmartStore.Web.Framework.UI.MenuPublisher.<>c__DisplayClass7.<RegisterMenus>b__2()
   at SmartStore.Core.Caching.CacheManager`1.Get[T](String key, Func`1 acquirer, Nullable`1 cacheTime)
   at SmartStore.Web.Framework.UI.MenuPublisher.RegisterMenus(TreeNode`1 rootNode, String menuName)
   at SmartStore.Web.Controllers.CatalogHelper.<GetCategoryMenu>b__61()
   at SmartStore.Core.Caching.CacheManager`1.Get[T](String key, Func`1 acquirer, Nullable`1 cacheTime)
   at SmartStore.Web.Controllers.CatalogHelper.GetCategoryMenu()
   at SmartStore.Web.Controllers.CatalogController.CategoryNavigation(Int32 currentCategoryId, Int32 currentProductId)
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by muratcakir** [comment]
*Tried* to fix this in [47a2a00 ](https://github.com/smartstoreag/SmartStoreNET/commit/47a2a00d9ea88fd9bb920c5c1fb9c85c925e4fe6)

I couldn't reproduce this behaviour, so I *blindly* optimized and enhanced the code. Could you please pull the latest commit from branch 2.x and test it again?

**Comment by andriisydor** [comment]
Could u remove private static object s_lock = new object(); or make it not static. It does not make any sense being static or lock blocks in general
lock (s_lock)
			{
					if (_assemblySkipLoadingRegex == null)
					{
						_assemblySkipLoadingRegex = new Regex(_assemblySkipLoadingPattern, RegexOptions.IgnoreCase | RegexOptions.Compiled | RegexOptions.Singleline);
					}
				}

**Comment by muratcakir** [comment]
No I can't ;-) Because it's a singleton instance and locking is required for this particular code block. I could remove `static` though, but it absolutely makes no difference.

Anyway, did you have the opportunity to test the fixed code?
