### ISSUE TITLE
CacheManager `Exception of type 'System.OutOfMemoryException' was thrown.` in RemoveByPattern

### ISSUE THREAD

**Issue by andriisydor** [smartstoreag/SmartStoreNET#723]
Related to #720 
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Go3945(RegexRunner )
   at System.Text.RegularExpressions.RegexRunner.Scan(Regex regex, String text, Int32 textbeg, Int32 textend, Int32 textstart, Int32 prevlen, Boolean quick, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run(Boolean quick, Int32 prevlen, String input, Int32 beginning, Int32 length, Int32 startat)
   at System.Text.RegularExpressions.Regex.IsMatch(String input)
   at SmartStore.Core.Caching.CacheManager`1.RemoveByPattern(String pattern)
   at SmartStore.Services.Common.GenericAttributeService.UpdateAttribute(GenericAttribute attribute)
   at SmartStore.Web.Framework.Controllers.StoreLastVisitedPageAttribute.OnActionExecuting(ActionExecutingContext filterContext)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.InvokeActionMethodFilterAsynchronouslyRecursive(Int32 filterIndex)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__31(AsyncCallback asyncCallback, Object asyncState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.Begin(AsyncCallback callback, Object state, Int32 timeout)
   at System.Web.Mvc.Async.AsyncResultWrapper.Begin[TResult](AsyncCallback callback, Object state, BeginInvokeDelegate beginDelegate, EndInvokeDelegate`1 endDelegate, Object tag, Int32 timeout)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

there is `EnterWriteLock()` but it's not needed at all, it should be replaced to Add/Remove/Contains methods in `ICache` implementations and if required but as close as possible to calling cache item

**Comment by muratcakir** [comment]
An `ICache` implementation is **by design** not thread safe. Instead, the`IsSingleton` property tells the wrapping `ICacheManager` whether write access should be synced. Otherwise thread safety had to be implemented individually in every singleton cache provider.

Concerning `EnterWriteLock` in `RemoveByPattern` or `Clear`: it's an atomic operation! Locking every single item would result in much higher resource usage.
