### ISSUE TITLE
Compilation fails with Visual Studio 2015

### ISSUE THREAD

**Issue by sherry-ummen** [smartstoreag/SmartStoreNET#795]
Hi,

I am using 2.x branch.

When I compile the code with VS2015 I get the following exception.

Severity	Code	Description	Project	File	Line
Error		The "GenerateResource" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Tasks.ResGenDependencies.GetResXFileInfo(String resxFile)
   at Microsoft.Build.Tasks.GenerateResource.ShouldRebuildResgenOutputFile(String sourceFilePath, String outputFilePath)
   at Microsoft.Build.Tasks.GenerateResource.GetResourcesToProcess(List`1& inputsToProcess, List`1& outputsToProcess, List`1& cachedOutputFiles)
   at Microsoft.Build.Tasks.GenerateResource.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	SmartStore.Data

**Comment by 18583690825** [comment]
But i cleaned and rebuilded,didn't help.Anyone help me please?
