### ISSUE TITLE
Scheduled Tasks stop executing

### ISSUE THREAD

**Issue by davza** [smartstoreag/SmartStoreNET#845]
The scheduled tasks stop being processed at various undetermined times.

The only thing that I have at the moment is a screen-shot from the Scheduled tasks page.
Have you seen this before? What can I look for? Would an error be logged anywhere?
Could this be related to #844, there are no details on that issue so I could not determine if they were related.

The time was +-09:50 when the screenshot was taken

![scheduledtasknotrunning](https://cloud.githubusercontent.com/assets/8984353/12070248/ce06856c-b06f-11e5-93bf-0eb0cb85e79d.png)

**Comment by muratcakir** [comment]
This could indeed be related to #844, but I'm not really sure.

Questions:

* Does this happen on your local machine? If not, did you make sure that your store URL is valid? 
* Does your local time zone differ from the server time zone?

**Comment by davza** [comment]
Hi,
I have not had it happen on my local machine, only in production.
It does not happen very frequently, maybe once a week, but it has happened twice in the same day, about 6 hours apart.

The timezone is different, but I do not think this is part of the problem.
I forgot to mention that in order to get the scheduled task to be run / processed again you need to restart the application.

I do have a warning that the URL does not match then I login to the admin site using the non-www prefixed url and the warning is not there when I login using the www prefixed url, or any of the other store sub-domains, the main store has got both the www and non-www urls set in the host headers, so:

Main store:
Store URL: http://www.smartstore.com/
HOST values: www.smartstore.com,smartstore.com

I get the URL warning when I login to smartstore.com, but not www.smartstore.com


Is there any logging that happens when the tasks are run that I can check?

**Comment by muratcakir** [comment]
During execution of tasks, errors are logged in **[Root]/SmartStore.log**. Please have a look at this file and tell me about any scheduler specific entry (usually they begin with *Error while calling TaskScheduler endpoint [...]*)

**Comment by davza** [comment]
Hi 

The errors is the file are:

SmartStore Error: 2 : ERROR: Error while calling TaskScheduler endpoint 'http://www.mystore.com/TaskScheduler/Sweep'. HTTP 503, Service Unavailable
    DateTime=2016-01-01T01:09:29.4495274Z
SmartStore Error: 2 : ERROR: Error while calling TaskScheduler endpoint 'http://www.mystore.com/TaskScheduler/Sweep'. HTTP 503, Service Unavailable
    DateTime=2016-01-01T01:10:24.6144135Z

**Comment by muratcakir** [comment]
Is *www.mystore.com* just a replacement value or is it the original host name? If yes, then it is is the cause. If not, then HTTP 503 indicates that the server is temporarily not available, probably due to a HTTP timeout. Where is your store hosted (which company)? I'll dig into it.

**Comment by davza** [comment]
Hi, Yes, it is a replacement URL.
The store is hosted on azure, Northern Europe region.

I would understand that, but why would the scheduler not try again? 
You can see from the screen-shot that the sending mails had not been run for 6 hours when it should be run every minute.
This also prevents all the subsequent tasks from running.

I don't think that the error in the log file relate to the schedule not running, I think they might have been caused by the "Delete guests" and "Update currency exchange rates" trying to run at the same time that the "Delete logs" task was running. (They all last ran at 2016-01-01 03:00 AM), which is the same time as on the log as I am 2 hours ahead of UTC and the servers timezone.
and the "Send emails" task was last run at "2016-01-01 03:06"

I had initially thought that it could have been caused by tasks running at the same time, but based on the above that does not seem likely.
To try and stop task running at the same time I have disabled the "Update currency exchange rates" task and changed the "Delete logs" task to run at 2 minutes past the hour (2 1 * * *)

**Comment by davza** [comment]
it stopped again this morning at 2016-01-07 01:48 UTC.
There were no new messages in the SmartStore.log file:


![scheduledtasknotrunning_20160107](https://cloud.githubusercontent.com/assets/8984353/12177627/b8dc0f44-b575-11e5-9d5e-0d204cbd2d81.png)

**Comment by muratcakir** [comment]
This is all very strange. But I'm pretty blind here and don't know where to begin bug hunting as it is most likely an environmental issue.

Concurrency is definitely not the cause: the scheduler is smart enough to handle any number of concurrent tasks properly.

Please pull my latest commit df31f4f375026c4129096ca0cc0cecdfbb7a1863, which logs the state of the sweep call every minute in `[Root]/App_Data/SmartStore.log`. I have to know in which stage the scheduler stucks. It's a quick 'n dirty logging implementation, which I'll remove in another commit.

It would help me a lot if you could run your store with this latest source and send me the log file later.

**Comment by davza** [comment]
Thanks, I updated the code on Thursday night and will post the logs when there is a problem again.

**Comment by davza** [comment]
Hi, Just an update, this has been running fine for the last week.
I'll update in a week again if there are no problems, else when they happen.

**Comment by davza** [comment]
Hi, It stopped last night again.
There was nothing extra written in the log file, I have attached a piece of the log, I added 2 blank line where I restarted the application.

I only took the screen-shot after restarting the applicaion, but it was before the first scheduled task had been run, so you can see the last run-times, and the "Send emails" and "Delete guests" tasks were listed as "waiting...". The rest of the tasks are disabled.

The only other errors logged round this time were 2:
"System.Web.HttpException
A potentially dangerous Request.Path value was detected from the client (&)."
Errors at server time:
"2016-01-15 17:32" 
"2016-01-15 22:53"
both were from bing-bot trying to index a page from the old (pre-smartstore) site and I'm pretty sure are not related.

![image](https://cloud.githubusercontent.com/assets/8984353/12371499/3f25d2aa-bc3e-11e5-9b01-4e183c5ac96c.png)

I have also included the raw web server log file, there was either an application recycle or just a log file rotation that happened at about 21:45 (the same time the last scheduled task tempted to run.
[raw_http.txt](https://github.com/smartstoreag/SmartStoreNET/files/92845/raw_http.txt)

There is no /TaskScheduler/Sweep record for 21:45, and the first call to the host use *.mystore.com, not www.mystore.com
I'm not sure what affect this would have.

I also found this in the System-> Log menu
![image](https://cloud.githubusercontent.com/assets/8984353/12371739/c83287b6-bc46-11e5-9069-0f0f76b6cf39.png)

But that was 20 minutes before it stopped working. This was the first time the scheduler used localhost, the other times there were error it either used the correct domain name or there was no log entry for initialising the Scheduler.

Please let me know if I can look for anything else.

**Comment by davza** [comment]
Hi, it happened this morning:

There was nothing new in the smartstore.log file, only the normal:

SmartStore Verbose: 16 : VERBOSE: TaskScheduler Sweep called successfully: 1 of 1 pending tasks executed
    DateTime=2016-01-17T04:08:06.5724561Z
SmartStore Verbose: 16 : VERBOSE: TaskScheduler Sweep called successfully: 1 of 1 pending tasks executed
    DateTime=2016-01-17T04:09:06.5704949Z

Here is the http log:
[raw_http_20160117.txt](https://github.com/smartstoreag/SmartStoreNET/files/93212/raw_http_20160117.txt)

Again, the system is calling /TaskScheduler/Sweep using www.mystore.com fine (at 04:08:06), then the calls stop.
This time there was no log file rotation, and nothing in the log to indicate that the application had been recycled, but the next activity is 5 minutes later to *.mystore.com

There were no errors on the server at the time, the most recent error was a 404 for an old page at 03:58:18, Server time.

![image](https://cloud.githubusercontent.com/assets/8984353/12375986/b1410ab0-bce5-11e5-91be-481667c4a43f.png)

**Comment by muratcakir** [comment]
First of all, thank you for your time and your valuable input. It's highly appreciated.

This all is very strange indeed. The base URL never should be *localhost* in a hosted environment. Maybe I have to tweak the detection mechanism. But for now I'm more interested in **web.config > sm:TaskSchedulerBaseUrl**. Does the task scheduler operate reliably when we specify an explicit base url, where the host name part is NOT internal or fake, but the real url of your hosted shop (NOT localhost, mystore.com or similar)?

Could you please specify a valid url in your web.config and observe it again for a few days? That'd be really great!

**Comment by davza** [comment]
Thanks for the feedback, what format do I need to use for the attribute?
<add key="sm:TaskSchedulerBaseUrl" value="www.mystore.com"/>
or 
<add key="sm:TaskSchedulerBaseUrl" value="http://www.mystore.com"/>

and I'm assuming this goes straight into the <appsettings>?

The store does not currently have an ssl certificate, but there will be one in the following month

**Comment by muratcakir** [comment]
http://*yourvalidhostname*/taskscheduler. The last segment is very important (taskscheduler). And yes, it goes into *appSettings*.

**Comment by davza** [comment]
thanks, have just updated the web.config file.
I'll post as soon as I see anything, or in a week if there is no news.

**Comment by davza** [comment]
This has been working fine since the last update (for the last 17 days).
I'll check again in another 2 weeks (after a month) and update this.

Thanks again for the suggestions / debugging

**Comment by vitorrubio** [comment]
I can't execute the sendmail schedule task. 
This is the error i'm getting:

Frequency
3
Log level
Error
Short message
An error occurred while executing the command definition. See the inner exception for details.
Content hash
d+JEuIKe19FJE5GkUHd5GA==
IP address
177.140.127.82
Customer
vitorrubio@gmail.com
Page URL
http://loja.tecnun.com.br/Admin/ScheduleTask/GetRunningTasks
Referrer URL
http://loja.tecnun.com.br/Admin/ScheduleTask/List
Created on
1/2/2017 7:03:20 PM
Updated on
1/2/2017 7:03:34 PM
Full message
An error occurred while executing the command definition. See the inner exception for details.
--------------------
   at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
   at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.Infrastructure.DefaultExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__3[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Any[TSource](IQueryable`1 source)
   at SmartStore.Services.Tasks.ScheduleTaskService.HasRunningTasks()
   at SmartStore.Admin.Controllers.ScheduleTaskController.GetRunningTasks()
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass33.<BeginInvokeActionMethodWithFilters>b__32(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)

**Comment by profnimrod** [comment]
Since upgrading to 3.1 (on May 1) none of my scheduled tasks have run (I just noticed today when a customer complained that they couldn't reset their password), including processing the Message Queue every minute.  I have added:

`<add key="sm:TaskSchedulerBaseUrl" value="https://store.inergysystems.com/taskscheduler" />
`
to the Web.config, but still the "Send emails" and "Delete guests" tasks are stuck at "Waiting..."

I can't find anything at [Root]/SmartStore.log on the server.

Any ideas?

**Comment by muratcakir** [comment]
Your scheduler endpoint is secured by SSL. We recently [fixed a SSL/TLS issue](https://github.com/smartstoreag/SmartStoreNET/commit/f7876173fa728dcdc89e18b338dd3046165dfbb1), which led to connection failures on some server environments. Maybe your shop/server is also affected.

All you need to do is to add this code to the very beginning of the method `Application_Start()` in your `Global.asax`:

```c#
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;
ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, errors) => true;
```

**Comment by profnimrod** [comment]
Excellent - pleased to find this is known problem with a solution.  I wonder if you could clarify where this is added.  I installed the version that is downloadable from the homepage (https://www.smartstore.com/en/net).  This version does not contain a Global.asax.cs file to add your proposed code.  Do I need to add an empty one and add the required method and code?  Or, do I need to download the source from GitHub and recompile?

**Comment by muratcakir** [comment]
You need the souce code version. You could also wait for V3.1.5 to be released which is scheduled for 25.05.2018.

**Comment by profnimrod** [comment]
OK, I'll give that a go.  I'll backup my existing database first... but if I reference the existing database when installing the latest version based on the source code, will my existing data and settings carry over OK?

**Comment by muratcakir** [comment]
Yes, it will.

**Comment by profnimrod** [comment]
Thanks - I downloaded the latest source from GitHub, compiled it, published SmartStore.Web to my server, and copied over the App_Data from my original installation.  I can get to the store, and all my data seems to have been carried over. Good.  However, I get a 404 when attempting to view the admin pages.  Any ideas?

**Comment by profnimrod** [comment]
All fixed using the latest code for 3.1.5 - thanks!

**Comment by isengineers** [comment]
I am facing similar issue like davza faced.. task scheduler is not working.. i am not good at programming in the code.. but if you suggest where to edit what i can do it...

![image](https://user-images.githubusercontent.com/54472831/63636887-1cf7ba00-c693-11e9-848f-fc5ca16305ae.png)

**Comment by isengineers** [comment]
> I

Can you elaborate more on what changes you have done? i am facing similar issue like that..

**Comment by davza** [comment]
> I am facing similar issue like davza faced.. task scheduler is not working.. i am not good at programming in the code.. but if you suggest where to edit what i can do it...
> 
> ![image](https://user-images.githubusercontent.com/54472831/63636887-1cf7ba00-c693-11e9-848f-fc5ca16305ae.png)



> Can you elaborate more on what changes you have done? i am facing similar issue like that..

@isengineers 
The error message is very descriptive, best you get a programmer / software developer to help you sort out the problem. 
GitHub issues should only be used for reporting problems in the coding or bugs in the system.

**Comment by PixelDevelopers** [comment]
If anyone else experiences the issue, ensure the STORE URL is HTTP:// - That's what the Scheduler Uses, your Store will redirect to SSL if the Use SSL toggle is on and then ensure the Secure URL is HTTPS://
